# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 117e6b3a6d0cafca4e802216163d2ef16904c407f666675ddd1c3a155f545fb10bfcbcb46f52e6b24fc55e028db0e5ee46fe4f527ddf6a56082bef0519558857

test:
  secret_key_base: bbcdb7e15f243f41dcd458502570d03c09dfe479a8857fb7aa317e731e16e42489cd2b692a9b825ab83afe6d8f908b49cd52e03ee8976e8014cdb9ea1aa81363

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
